@echo off
echo 正在安装 Django...
"D:\青软\Python\安装\python.exe" -m pip install django
echo.
echo 安装完成！现在创建数据库...
"D:\青软\Python\安装\python.exe" manage.py migrate
echo.
echo 正在创建管理员账号...
"D:\青软\Python\安装\python.exe" manage.py createsuperuser
echo.
echo 启动服务器...
"D:\青软\Python\安装\python.exe" manage.py runserver 8000
pause
