# Generated by Django 6.0.4 on 2026-04-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='报到时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.studentinfo', verbose_name='学生信息')),
            ],
            options={
                'verbose_name': '报到记录',
                'verbose_name_plural': '报到记录',
                'ordering': ['-register_time'],
            },
        ),
    ]
