# Generated by Django 6.0.4 on 2026-05-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentinfo_registrationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=4, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '验证码记录',
                'verbose_name_plural': '验证码记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/%Y/%m/%d/', verbose_name='身份证照片'),
        ),
    ]
