# Generated by Django 6.0.4 on 2026-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_verificationcode_studentinfo_id_card_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='id_card_photo',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id_card_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/%Y/%m/%d/', verbose_name='身份证反面照片'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id_card_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/%Y/%m/%d/', verbose_name='身份证正面照片'),
        ),
    ]
