# Generated by Django 4.2 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studentinfo_id_card_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核驳回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='驳回原因'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='dormitory_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宿舍号'),
        ),
    ]
