# Generated by Django 6.0.4 on 2026-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_studentinfo_id_card_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='is_name_verified',
            field=models.BooleanField(default=False, verbose_name='姓名审核状态'),
        ),
    ]
