# Generated by Django 4.2 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentinfo_review_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory_number', models.CharField(max_length=50, unique=True, verbose_name='宿舍号')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('capacity', models.IntegerField(default=4, verbose_name='容纳人数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='宿舍描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '宿舍信息',
                'verbose_name_plural': '宿舍信息',
                'ordering': ['dormitory_number'],
            },
        ),
    ]
